### ISSUE TITLE
Cannot read property `mainModule`

### ISSUE THREAD

**Issue by nukkamoto** [JsonHunt/atom-auto-panes#1]
```
TypeError: Cannot read property 'mainModule' of undefined
  at module.exports.AtomAutoPanes.onNewEditor (C:\Users\vcaushi\Dropbox\.atom\packages\auto-panes\lib\auto-panes.coffee:34:59)
  at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\vcaushi\AppData\Local\atom\app-0.181.0\resources\app\src\workspace.js:272:9)
  at Object.module.exports.AtomAutoPanes.toggle (C:\Users\vcaushi\Dropbox\.atom\packages\auto-panes\lib\auto-panes.coffee:111:40)
  at atom-workspace.subscriptions.add.atom.commands.add.auto-panes:toggle (C:\Users\vcaushi\Dropbox\.atom\packages\auto-panes\lib\auto-panes.coffee:30:85)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\vcaushi\AppData\Local\atom\app-0.181.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\vcaushi\AppData\Local\atom\app-0.181.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\vcaushi\AppData\Local\atom\app-0.181.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\vcaushi\AppData\Local\atom\app-0.181.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\vcaushi\AppData\Local\atom\app-0.181.0\resources\app\src\window-event-handler.js:176:20)
```

I got an error when I tried to toggle.

I had 2 tabs open, a file and the settings page.

If you need anything let me know :)

**Comment by JsonHunt** [comment]
Thanks for logging the issue
It was caused by me changing the package name to comply with atom guidelines and not correcting config lookups. 
It should work now. Enjoy, and check out my save-commands package
